apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: kubeshark-hub-network-policy
  namespace: sock-shop
spec:
  podSelector:
    matchLabels:
      name: mizutest-sctp-server
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - ports:
        - protocol: SCTP
          port: 50051
  egress:
    - {}
