---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mizutest-ldap-server
  namespace: sock-shop
  labels:
    app: mizutest-ldap-server
    protocol: v3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mizutest-ldap-server
  template:
    metadata:
      labels:
        app: mizutest-ldap-server
        protocol: v3
    spec:
      containers:
        - name: mizutest-ldap-server
          image: osixia/openldap:1.5.0
          ports:
            - containerPort: 389
