---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ldap-server-v3
  labels:
    app: openldap
    protocol: v3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openldap
  template:
    metadata:
      labels:
        app: openldap
        protocol: v3
    spec:
      containers:
        - name: openldap
          image: osixia/openldap:1.5.0
          ports:
            - containerPort: 389
