---
apiVersion: v1
kind: Service
metadata:
  name: ldap-server-v3
  labels:
    app: openldap
    protocol: v3
spec:
  ports:
    - port: 389
      targetPort: 389
  selector:
    app: openldap
    protocol: v3
  type: ClusterIP
