---
apiVersion: v1
kind: Service
metadata:
  name: mizutest-ldap-client
  namespace: sock-shop
  labels:
    app: mizutest-ldap-client
    protocol: v3
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: mizutest-ldap-client
    protocol: v3
  type: ClusterIP
