apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: 'true'
  labels:
    app: mizutest-radius-server
    name: mizutest-radius-server
    version: v0.1.0
  name: mizutest-radius-server
  namespace: sock-shop
spec:
  ports:
  - port: 1812
    protocol: UDP
    targetPort: 1812
  selector:
    name: mizutest-radius-server
