apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: 'true'
  labels:
    app: mizutest-diameter-server
    name: mizutest-diameter-server
    version: v0.1.0
  name: mizutest-diameter-server
  namespace: sock-shop
spec:
  ports:
  - port: 3868
    protocol: TCP
    targetPort: 3868
  selector:
    name: mizutest-diameter-server
