apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mizutest-diameter-sctp-server
    name: mizutest-diameter-sctp-server
    version: v0.1.0
  name: mizutest-diameter-sctp-server
  namespace: sock-shop
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mizutest-diameter-sctp-server
  template:
    metadata:
      labels:
        app: mizutest-diameter-sctp-server
        name: mizutest-diameter-sctp-server
        version: v0.1.0
    spec:
      containers:
        - name: mizutest-diameter-sctp-server
          image: kubeshark/mizutest-diameter-server:latest
          imagePullPolicy: Always
          args:
          - -network_type
          - sctp
          ports:
          - containerPort: 3868
          resources:
            limits:
              cpu: 75m
              memory: 100Mi
            requests:
              cpu: 10m
              memory: 10Mi
      nodeSelector:
        kubernetes.io/os: linux
