---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mizutest-redis-go
  labels:
    name: mizutest-redis-go
  namespace: sock-shop
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mizutest-redis-go
  template:
    metadata:
      labels:
        name: mizutest-redis-go
    spec:
      containers:
      - name: mizutest-redis-go
        image: mertyildiran/mizutest-redis-go:latest
        imagePullPolicy: Always
        command: ["./run.sh"]
        resources:
          limits:
            cpu: 200m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 6379
        # securityContext:
        #   runAsNonRoot: true
        #   runAsUser: 10001
        #   capabilities:
        #     drop:
        #       - all
        #     add:
        #       - NET_BIND_SERVICE
        #   readOnlyRootFilesystem: true
      nodeSelector:
        beta.kubernetes.io/os: linux
