apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sock-shop
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/kubeshark/sock-shop-demo.git
    targetRevision: HEAD
    path: deploy/kubernetes/complete-demo.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: sock-shop